done
basiacarvalho/kreativstorm-project1 pull request #21
Opened 2024-02-02 23:24 UTC by Mohamed9820m

2024-02-02 23:39 UTC, basiacarvalho requested changes

2024-02-02 23:39 UTC, basiacarvalho commented on css/style.css
> +
There are two empty lines here. One is enough

2024-02-02 23:39 UTC, basiacarvalho commented on css/style.css
> +
Many empty lines. Please have a look at the rest of the code, I won't write any more comments regarding these empty lines

2024-02-02 23:39 UTC, basiacarvalho commented on pages/blog.htm
> +
There are many empty lines in this file. Please remove them.

2024-02-03 08:22 UTC, basiacarvalho commented
Hi,

I've just finished checking Lezanders pull request and I had another look at yours. 
Unfortunately, there are some issues and conflicts to take care of that we don't have time for now.
Apart from that, I checked from your local branch that it changes the appearance of other pages.
I've just talked to Elisabeth as Lezanders is not available, and we decided to not merge your pull request now for the benefit of the whole group. During the presentation, I will let Branko know that your pull request is open.

Basia

2024-02-03 09:19 UTC, Mohamed9820m commented
i fix all the issues that you send them what is missing !


Le sam. 3 févr. 2024 à 09:22, basiacarvalho ***@***.***> a
écrit :

> Hi,
>
> I've just finished checking Lezanders pull request and I had another look
> at yours.
> Unfortunately, there are some issues and conflicts to take care of that we
> don't have time for now.
> Apart from that, I checked from your local branch that it changes the
> appearance of other pages.
> I've just talked to Elisabeth as Lezanders is not available, and we
> decided to not merge your pull request now for the benefit of the whole
> group. During the presentation, I will let Branko know that your pull
> request is open.
>
> Basia
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/basiacarvalho/kreativstorm-project1/pull/21#issuecomment-1925214634>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR66Z4RVRYTPBBJYUCFJD3DYRXXWBAVCNFSM6AAAAABCXOGOG6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMRVGIYTINRTGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-18 11:15 UTC, closed without merging