Update style.css
basiacarvalho/kreativstorm-project1 pull request #7
Opened 2024-01-31 09:23 UTC by elic4vet

I added some styles on the hero section, i will continue working on this subject later. Hope it's okay for you :)

2024-01-31 11:36 UTC, elic4vet commented
I had to repost my pull request because i couldn't find my changes concerning the html file.  Hope it's okay for you :)

2024-01-31 13:06 UTC, elic4vet commented
i created the about us section and added the corresponding link that navigates from home to the about section and back to home

2024-01-31 14:14 UTC, basiacarvalho approved these changes
Hi, I left 2 comments :)

2024-01-31 14:14 UTC, basiacarvalho commented on css/style.css
> +}
Decide whether you want to always leave one line space between style declarations or have it all one by one. I read on the internet that is better to keep one empty line in style for readability (so I always separate style declarations with one line).

2024-01-31 14:14 UTC, basiacarvalho commented on index.html
> +      <section class="hero">
You can leave the common class "section" in the section tag, and apart from that add the second class name "hero" and put in "hero" only what varies from the normal "section" styling.

2024-02-01 11:23 UTC, elic4vet commented
I added the course link on the about us section

2024-02-01 12:35 UTC, elic4vet commented
•	I added an image to the hero section.
•	I also added an image container to better divide and organize these two sections.
•	I added styles for the two divs and the image.

- [ ] 	I need to work later on the style of the page and @media queries for the mob + tablet version.

2024-02-01 12:45 UTC, basiacarvalho approved these changes

2024-02-01 12:45 UTC, basiacarvalho commented on index.html
> +              alt="a person sitting in front of a computer"
I would probably write alt="an open laptop with code display on a desk with a plant and a mug" for the hero img

2024-02-01 12:50 UTC, basiacarvalho requested changes
Hi, 

One thing to fix - look at my proposition of an "alt" for hero img :) 
"an open laptop with code displayed on a desk with a plant and a mug"

2024-02-01 18:44 UTC, elic4vet commented
I changed the text description of the alt as suggested before

2024-02-01 19:34 UTC, basiacarvalho approved these changes

2024-02-01 19:37 UTC, merged